framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: false
        cookie_samesite: null
        storage_factory_id: session.storage.factory.native

    csrf_protection: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
